# -*- coding: utf-8 -*-
"""Cancer Detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AahfYHmBUzl0M5Zt_5TwC1WT-UKbbKm9

#**Cancer Detection Program**

**Importing Library**
"""

import pandas as pd

"""Import Dataset"""

Cancer = pd.read_csv('https://raw.githubusercontent.com/YBIFoundation/Dataset/main/Cancer.csv')

"""Describe Dataset"""

Cancer.describe()

"""Visualize Dataset"""

Cancer.head(5)

"""Data information"""

Cancer.info()

"""Define feature variable (x) and target variable (y)"""

x = Cancer[['radius_mean','texture_mean']]
y = Cancer['concave points_mean']

"""Spilting Dataset into Train and Test datasets"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.7,random_state=2529)

"""Performing Linear Regression"""

from sklearn.linear_model import LinearRegression
LinR = LinearRegression()
LinR.fit(x_train,y_train)

"""Prediction"""

y_pred = LinR.predict(x_test)

"""Mean Absolute Error"""

from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_pred,y_test)

from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_pred,y_test)

